name: Docker Image CI
on:
  release:
    types: [published]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  build:
    runs-on: ubuntu-latest
    needs: Release
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get Version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ppchen7247/test-docker-image-release:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push ppchen7247/test-docker-image-release:${{steps.vars.outputs.tag}}
